# Generated by Django 4.1.6 on 2023-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('donor', models.BooleanField()),
                ('inventory', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
