# Generated by Django 4.1.6 on 2023-02-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addUser',
            new_name='User',
        ),
    ]
