# Generated by Django 4.1.6 on 2023-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_adduser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepient_id', models.IntegerField()),
                ('donor_id', models.IntegerField()),
                ('food', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
