# Generated by Django 4.1.6 on 2023-02-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inventory',
            field=models.TextField(blank=True),
        ),
    ]
